# Site settings
title: Mahad Qureshi
email: hello@mahadqureshi.com
description: Mahad is a designer focused on shaping solutions that bridge products and humans together.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: mahdqureshi
github_username:  mahdqureshi
permalink: /:title

# Build settings
markdown: kramdown

collections:
  studies:
    output: true
    permalink: /:collection/:name