# Site settings
title: Mahad Qureshi | Digital Product Designer
email: hello@mahadqureshi.com
description: Mahad is a designer and maker based in San Francisco, CA. He is focused on shaping solutions that bridge products and consumers together through visual design, user research, and product strategy.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: mahdqureshi
github_username:  mahdqureshi
permalink: /:title

# Build settings
markdown: kramdown
